spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskflow
    username: taskflow_user
    password: 123456789
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate   # We'll create tables manually or with Flyway later
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    access-token-expiration: 900000        # 15 minutes
    refresh-token-expiration: 604800000    # 7 days